### ISSUE TITLE
optional function to compute props

### ISSUE THREAD

**Issue by derhuerst** [juliuste/geojson-svgify#7]
I would be useful to optionally pass in a function `computeProps` that gets passed the current GeoJSON feature being converted to SVG and returns virtual-dom props.

e.g. my current use case:

```js
const computeProps = (feature) => ({id: feature.properties.country})
```

would you mind if submitted a PR?

**Comment by derhuerst** [comment]
bump. (:

**Comment by juliuste** [comment]
Feel free to PR 👍
